# Generated by Django 5.2.6 on 2025-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
